' ---------------------start of iLogic code---------------------
'This code allows the user to define two custom iproperties within the part or drawing and enter them into an inputbox. These properties wil be defined as custom iproperties within the file. 

Dim propertyName1 As String = "New Property 1"
Dim propertyName2 As String = "New Property 2"


'define custom property collection
oCustomPropertySet = ThisDoc.Document.PropertySets.Item("Inventor User Defined Properties")

Try
'set property value1 SC
oProp = oCustomPropertySet.Item(propertyName1)
Catch
' Assume error means not found so create it
oCustomPropertySet.Add("", propertyName1)
End Try

Try
'look for property2 NSC
oProp = oCustomPropertySet.Item(propertyName2)
Catch
' Assume error means not found so create it
oCustomPropertySet.Add("", propertyName2)
End Try

Dim strNewProp1 As String
Dim strNewProp2 As String

'get values from user
strNewProp1 = InputBox("Enter input prompt for user to define property 1", "iLogic", "N/A") 'N/A default value
strNewProp2 = InputBox("Enter input prompt for user to define property 2", "iLogic", "N/A") 'N/A default value

'set custom property values
iProperties.Value("Custom", "New Property 1") = strNewProp1
iProperties.Value("Custom", "New Property 2") = strNewProp2

iLogicVb.UpdateWhenDone = True

' ---------------------end of iLogic code ---------------------
