'start of ilogic code

doc = ThisDoc.Document
 'check file type 
If doc.DocumentType = kPartDocumentObject Then
MessageBox.Show("This is a part file.", "iLogic")

Else If doc.DocumentType = kDrawingDocumentObject
MessageBox.Show("This is a drawing.", "iLogic")

Else If doc.DocumentType = kAssemblyDocumentObject Then

' get the active assembly
Dim oAsmCompDef As AssemblyComponentDefinition 
oAsmCompDef = ThisApplication.ActiveDocument.ComponentDefinition 


'set the Master LOD active
Dim oLODRep As LevelofDetailRepresentation
oLODRep = oAsmCompDef.RepresentationsManager.LevelOfDetailRepresentations.Item("Master")
oLODRep.Activate


 'Iterate through all of the occurrences and ground them.
Dim oOccurrence As ComponentOccurrence 
For Each oOccurrence In oAsmCompDef.Occurrences
'check for and skip virtual components
If Not TypeOf oOccurrence.Definition Is VirtualComponentDefinition Then
oOccurrence.Grounded = True
Else
End If 
Next

Dim oAssDoc As AssemblyDocument
oAssDoc = ThisApplication.ActiveDocument
Dim oConstraint As AssemblyConstraint


RUSure = MessageBox.Show _
("Are you sure you want to delete all constraints?",  _
"iLogic",MessageBoxButtons.YesNo)


If RUSure = vbNo Then
Return
Else
          i = 0
          For Each oConstraint In oAssDoc.ComponentDefinition.Constraints
            
          oConstraint.Delete
            i = i + 1
          
          Next 
End If
MessageBox.Show(" A total of "&  i & " constraints were deleted.", "iLogic")
End If



